services:
  backend:
    image: 556565901230.dkr.ecr.ap-southeast-1.amazonaws.com/ekyc-backend:${IMAGE_TAG}
    ports:
      - "8000:8000"
    restart: always

  frontend:
    image: 556565901230.dkr.ecr.ap-southeast-1.amazonaws.com/ekyc-frontend:${IMAGE_TAG}
    ports:
      - "8501:8501"
    environment:
      - API_URL=${API_URL}
    restart: always
